AgileConnect/Controllers/ARMAppsController.cs
using AgileConnect.EncrDecr.cs;
using AgileConnect.Filter;
using ARMCommon.Helpers;
using ARMCommon.Interface;
using ARMCommon.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using NPOI.SS.Formula.Functions;
using Oracle.ManagedDataAccess.Client;
using StackExchange.Redis;
using System;
using System.Data;
using System.Data.Odbc;
using System.Data.SqlClient;

namespace AgileConnect.Controllers
{
    [ServiceFilter(typeof(SessionActionFilter))]
    [Authorize]
    public class ARMAppsController : Controller
    {
        private readonly IConfiguration _config;
        private readonly DataContext _context;
        private readonly IRedisHelper _redis;
        private readonly Utils _common;
        private string privateKey = EncDec.RefreshKey(16);
        private readonly IRedisConnection _redisConn;

        public ARMAppsController(IConfiguration config, IRedisHelper redis, DataContext context, Utils common, IRedisConnection redisConn)
        {
            _config = config;
            _redis = redis;
            _context = context;
            _common = common;
            _redisConn = redisConn;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ARMApp model)
        {
            if (ModelState.IsValid)
            {
                model.modifiedon = DateTime.Now;
                string rediskey = $"{Constants.REDIS_PREFIX.ARMRedisConfiguration.ToString()}_{model.AppName}";
                string dbkey = $"{Constants.DB_PREFIX.ARMConnectionString.ToString()}_{model.AppName}";

                // Clear existing Redis cache keys and values
                await ClearAllRedisCacheAsync();

                model.PrivateKey = privateKey;
                model.ConnectionName = EncDec.Encrypt(model.ConnectionName, privateKey);
                model.DataBase = EncDec.Encrypt(model.DataBase, privateKey);
                model.DBVersion = EncDec.Encrypt(model.DBVersion, privateKey);
                model.UserName = EncDec.Encrypt(model.UserName, privateKey);
                model.Password = EncDec.Encrypt(model.Password, privateKey);
                model.RedisIP = EncDec.Encrypt(model.RedisIP, privateKey);
                model.RedisPassword = EncDec.Encrypt(model.RedisPassword, privateKey);
                if (model.AppLogoBase64 == null || model.AppLogoBase64.Length == 0)
                {
                    return BadRequest("File not found");
                }
                using (var memoryStream = new MemoryStream())
                {
                    await model.AppLogoBase64.CopyToAsync(memoryStream);
                    var fileBytes = memoryStream.ToArray();
                    model.AppLogo = Convert.ToBase64String(fileBytes);
                }

                _context.Add(model);
                await _context.SaveChangesAsync();
                await _redis.StringSetAsync(rediskey, _common.GetRedisConnections(model.RedisIP, model.RedisPassword));
                await _redis.StringSetAsync(dbkey, _common.GetDBConnections(model.DataBase, model.UserName, model.Password, model.DBVersion,model.Sqlversion, model.ConnectionName));
                return RedirectToAction("List");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string appName)
        {
            var userGroup = GetUserGroupById(appName);
            var Key = userGroup.PrivateKey;
            if (Key != null)
            {
                userGroup.ConnectionName = EncDec.Decrypt(userGroup.ConnectionName, Key);
                userGroup.DataBase = EncDec.Decrypt(userGroup.DataBase, Key);
                userGroup.DBVersion = EncDec.Decrypt(userGroup.DBVersion, Key);
                userGroup.UserName = EncDec.Decrypt(userGroup.UserName, Key);
                userGroup.Password = EncDec.Decrypt(userGroup.Password, Key);
                userGroup.RedisIP = EncDec.Decrypt(userGroup.RedisIP, Key);
                userGroup.RedisPassword = EncDec.Decrypt(userGroup.RedisPassword, Key);

                var con = _common.GetRedisConnections(userGroup.RedisIP, userGroup.RedisPassword);
                string dbConnectionString = await _common.GetDBConfiguration(appName);
                var redisConfig = await _redisConn.GetRedisConfiguration(appName);
            }
            return View(userGroup);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string appName, ARMApp model)
        {
            if (appName != model.AppName)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    model.modifiedon = DateTime.Now;
                    string rediskey = $"{Constants.REDIS_PREFIX.ARMRedisConfiguration.ToString()}_{appName}";
                    string dbkey = $"{Constants.DB_PREFIX.ARMConnectionString.ToString()}_{appName}";


                    var result = await ClearAllRedisCacheAsync();

                    model.PrivateKey = privateKey;
                    model.ConnectionName = EncDec.Encrypt(model.ConnectionName, privateKey);
                    model.DataBase = EncDec.Encrypt(model.DataBase, privateKey);
                    model.DBVersion = EncDec.Encrypt(model.DBVersion, privateKey);
                    model.UserName = EncDec.Encrypt(model.UserName, privateKey);
                    model.Password = EncDec.Encrypt(model.Password, privateKey);
                    model.RedisIP = EncDec.Encrypt(model.RedisIP, privateKey);
                    model.RedisPassword = EncDec.Encrypt(model.RedisPassword, privateKey);
                    if (model.AppLogoBase64 == null || model.AppLogoBase64.Length == 0)
                    {
                        return BadRequest("Please upload logo");
                    }
                    using (var memoryStream = new MemoryStream())
                    {
                        await model.AppLogoBase64.CopyToAsync(memoryStream);
                        var fileBytes = memoryStream.ToArray();
                        model.AppLogo = Convert.ToBase64String(fileBytes);
                    }

                    _context.Update(model);
                    await _context.SaveChangesAsync();
                    await _redis.StringSetAsync(rediskey, _common.GetRedisConnections(model.RedisIP, model.RedisPassword));
                    await _redis.StringSetAsync(dbkey, _common.GetDBConnections(model.DataBase, model.UserName, model.Password, model.DBVersion,model.Sqlversion, model.ConnectionName));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppExists(model.AppName))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("List");
            }
            return View(model);
        }

        public IActionResult List()
        {
            var appLists = AppList();
            return View(appLists);
        }

        private ARMApp GetUserGroupById(string appName)
        {
            return GetUserGroupBy(appName);
        }

        private ARMApp GetUserGroupBy(string appName)
        {
            var app = _context.ARMApps.Find(appName);
            if (app == null)
                throw new KeyNotFoundException("App not found");
            return app;
        }

        private bool AppExists(string appName)
        {
            return _context.ARMApps.Any(e => e.AppName == appName);
        }

        private IEnumerable<ARMApp> AppList()
        {
            var appList = _context.ARMApps.ToList();
            return appList;
        }

        public string ConvertToBase64(IFormFile file)
        {
            using (var memoryStream = new MemoryStream())
            {
                file.CopyTo(memoryStream);
                var fileBytes = memoryStream.ToArray();
                return Convert.ToBase64String(fileBytes);
            }
        }

        [HttpPost]
        public async Task<IActionResult> TestConnection(string dbType, string connectionString)
        {
            try
            {
                IDbConnection connection;

                if (dbType.Equals("postgre", StringComparison.OrdinalIgnoreCase))
                {
                    connection = new NpgsqlConnection(connectionString);
                }
                else if (dbType.Equals("oracle", StringComparison.OrdinalIgnoreCase))
                {
                    connection = new OracleConnection(connectionString);
                }
                else if (dbType.Equals("mssql", StringComparison.OrdinalIgnoreCase))
                {
                    connection = new SqlConnection(connectionString);
                }
                else
                {
                    return Json(new { success = false, message = "Invalid database type specified." });
                }

                connection.Open();
                connection.Close();

                return Json(new { success = true, message = "Connection Successful." });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }


        [HttpPost]
        public async Task<IActionResult> GetServerIpAndPort(string dbVersion, string uid, string pwd, string database)
        {
            string connStr = $"DSN={dbVersion};Uid={uid};Pwd={pwd};";
            string connectionString = "";
            string dataSourceName = string.Empty;

            try
            {
                using (OdbcConnection connection = new OdbcConnection(connStr))
                {

AgileConnect/Controllers/ARMSignInController.cs
using AgileConnect.EncrDecr.cs;
using ARMCommon.Helpers;
using ARMCommon.Interface;
using ARMCommon.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System.Text;

namespace AgileConnect.Controllers
{


    public class ARMSignInController : Controller
    {
        private readonly IConfiguration _config;
        private readonly ITokenService _tokenService;
        private readonly DataContext _context;
        private readonly IRedisHelper _redis;
        public string key = "ARM-" + Guid.NewGuid().ToString();
        private string generatedToken = null;


        public ARMSignInController(IConfiguration config, ITokenService tokenService, DataContext context, IRedisHelper redis)
        {
            _config = config;
            _tokenService = tokenService;
            _context = context;
            _redis = redis;
        }
        public IActionResult Index()
        {
            return View("SignIn");
        }
        public IActionResult SignIn()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> SignIn(UserModel userModel)
        {
            if (string.IsNullOrEmpty(userModel.UserName) || string.IsNullOrEmpty(userModel.Password))
            {
                return (RedirectToAction("Error", "Home"));
            }

            IActionResult response = Unauthorized();


            if (System.IO.File.Exists(_config["ARMConfigFilePath"]))
            {
                string strJSON = String.Empty;

                var fileStream = new FileStream(_config["ARMConfigFilePath"], FileMode.Open, FileAccess.Read, FileShare.None);
                using (var streamReader = new StreamReader(fileStream, Encoding.UTF8))

                {
                    strJSON = streamReader.ReadToEnd();
                    var jObject = JObject.Parse(strJSON);
                    var privateKey = jObject["KeyData"]?["PrivateKey"]?.ToString();
                    var userId = jObject["AdminInstance"]?["admin"]?.ToString();
                    var Password = jObject["AdminInstance"]?["Password"]?.ToString().ToUpper();



                    // validate in File
                    if (userModel.UserName == userId && userModel.Password.ToUpper() == Password)
                    {
                        generatedToken = _tokenService.CreateToken(_config["Jwt:Key"].ToString(), _config["Jwt:Issuer"].ToString(),
                    userId);

                        if (generatedToken != null)
                        {
                            HttpContext.Session.SetString("TokenId", generatedToken);
                            HttpContext.Session.SetString("SessionId", key);
                            HttpContext.Session.SetString("Username", userModel.UserName);
                            await _redis.StringSetAsync(key, generatedToken);

                            var abc = _redis.StringGetAsync(key);
                            return RedirectToAction("Dashboard", "ARMInstance");
                        }
                        else
                        {
                            ViewBag.result = "UserName or Password is Incorrect";
                            ViewBag.color = "red";
                            return View();
                        }
                    }
                    else
                    {
                        ViewBag.result = "UserName or Password is Incorrect";
                        ViewBag.color = "red";
                        return View();
                    }


                }

            }
            else
            {
                ViewBag.result = "Config File is not Present at Location";
                ViewBag.color = "red";
                return View();
            }

        }


        public async Task<IActionResult> SignOut()
        {
            HttpContext.Session.Clear();
            return View("SignIn");
        }

        [Route("/error-development")]
        public IActionResult HandleErrorDevelopment(
        [FromServices] IHostEnvironment hostEnvironment)
        {
            if (!hostEnvironment.IsDevelopment())
            {
                return NotFound();
            }

            var exceptionHandlerFeature =
                HttpContext.Features.Get<IExceptionHandlerFeature>()!;

            return Problem(
                detail: exceptionHandlerFeature.Error.StackTrace,
                title: exceptionHandlerFeature.Error.Message);
        }

        [Route("/error")]
        public IActionResult HandleError() =>
            Problem();

        public IActionResult ResetCredential()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult ResetCredential(UserModel userModel)
        {
            if (string.IsNullOrEmpty(userModel.Email) || string.IsNullOrEmpty(userModel.Password))
            {
                return (RedirectToAction("Error", "Home"));
            }

            IActionResult response = Unauthorized();


            if (System.IO.File.Exists(_config["ARMConfigFilePath"]))
            {
                string strJSON = String.Empty;

                var fileStream = new FileStream(_config["ARMConfigFilePath"], FileMode.Open, FileAccess.Read, FileShare.None);
                using (var streamReader = new StreamReader(fileStream, Encoding.UTF8))

                {
                    strJSON = streamReader.ReadToEnd();
                    var jObject = JObject.Parse(strJSON);
                    var privateKey = jObject["KeyData"]?["PrivateKey"]?.ToString();
                    var EmailId = EncDec.Decrypt(jObject["AdminInstance"]?["AdminEmailId"]?.ToString(), privateKey);
                    var Password = EncDec.Decrypt(jObject["AdminInstance"]?["Password"]?.ToString(), privateKey);



                    // validate in File
                    if (userModel.Email == EmailId && userModel.Password == Password)
                    {
                        ViewBag.result = "Password will be sent to your EmailId Shortly";
                        ViewBag.color = "green";
                        return View();
                    }
                    else
                    {
                        ViewBag.result = "Email Id or Password is Incorrect";
                        ViewBag.color = "red";
                        return View();
                    }


                }

            }

            ViewBag.result = "Password will be sent to your EmailId Shortly";
            ViewBag.color = "green";
            return View();
        }

    }
}

AgileConnect/Views/AxModule/Create.cshtml
@model ARMCommon.Model.AxModule

@{
    ViewData["Title"] = "Create Module";
}


<h4>Create User Group</h4>
<a asp-controller="ARMSignIn" asp-action="SignOut" id="SignOut" class="redirectButton" title="redirectButton"> Sign Out </a>
<hr />

<div class="col-md-12">
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="input-group">
              <div class="form-group col-md-6">
                <label asp-for="appName" class="control-label"> App Name</label>

                  <div class = "col-md-8"> 
                  <input asp-for="appName" ReadOnly="true" id="txtkey"  class="form-control" />
@*
                   <select asp-for="AppName"
                            asp-items="@(new SelectList(Model.app1,"ID","Name"))" class="form-control">
                        <option disabled>Please select one</option>
                    </select>*@

            </div>

            </div>
                            <div class="form-group col-md-10">
                    <label asp-for="ModuleName" class="control-label"> Module Name</label>
                    <div class="col-md-10">
                        <input asp-for="ModuleName" class="form-control" />
                    </div>
                </div>
                <div class="form-group col-md-10">
                    <label asp-for="ModuleDescription" class="control-label"> Module Description</label>
                    <div class="col-md-10">
                        <input asp-for="ModuleDescription" class="form-control" />
                    </div>
                </div>
   
            <div class="form-group col-md-10">
                <div class="form-grou col-md-4">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </form>
</div>
<div>
     <a asp-controller="AxModule" asp-action="ListByApp" asp-route-Appname="@Html.ValueFor(model => model.appName)">  Back to List</a>
</div>

    @section Scripts {

    <style>
 
        a#SignOut {
    position: absolute;
    top: 19px;
    right: 40px;
    font-size: large;
}
    </style>
 
}

AgileConnect/Views/AxModule/Delete.cshtml
@model ARMCommon.Model.AxModule

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AxModule</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModuleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModuleName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModuleDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModuleDescription)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AgileConnect/Views/AxModule/Edit.cshtml
@model ARMCommon.Model.AxModule

@{
    ViewData["Title"] = "Edit Module";
}


<h4>Create User Group</h4>
<a asp-controller="ARMSignIn" asp-action="SignOut" id="SignOut" class="redirectButton" title="redirectButton"> Sign Out </a>
<hr />

<div class="col-md-12">
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="input-group">

                 <div class="form-group col-md-12">
                <label asp-for="appName" class="control-label"> App Name</label>
                 <input asp-for="appName" ReadOnly="true" id="txtkey"  class="form-control" />
            </div>
                            <div class="form-group col-md-10">
                    <label asp-for="ModuleName" class="control-label"> Module Name</label>
                    <div class="col-md-10">
                        <input asp-for="ModuleName" class="form-control" />
                    </div>
                </div>
                <div class="form-group col-md-10">
                    <label asp-for="ModuleDescription" class="control-label"> Module Description</label>
                    <div class="col-md-10">
                        <input asp-for="ModuleDescription" class="form-control" />
                    </div>
                </div>
   
            <div class="form-group col-md-10">
                <div class="form-grou col-md-4">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </form>
</div>

<div>
     <a asp-controller="AxModule" asp-action="ListByApp" asp-route-Appname="@Html.ValueFor(model => model.appName)">  Back to List</a>
</div>
    @section Scripts {

    <style>
 
        a#SignOut {
    position: absolute;
    top: 19px;
    right: 40px;
    font-size: large;
}
    </style>
 
}

AgileConnect/Views/AxModule/ListByApp.cshtml
@model IEnumerable<ARMCommon.Model.AxModule>

@{
    ViewData["Title"] = "AxModule";
}

<h4>Module Lists</h4>
   <a asp-controller="ARMSignIn" asp-action="SignOut" id="SignOut" class="redirectButton" title="redirectButton"> Sign Out </a>
<p>
    <a asp-action="Create" asp-route-Appname=@ViewBag.result>Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ModuleName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModuleDescription)
            </th>
 
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ModuleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModuleDescription)
            </td>
 
 
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

                    <div class="col-sm-6"> 
     <a asp-controller="ARMApps" asp-action="List"  id="redirectApp" class="redirectButton" title="redirectButton"> View Connected Apps </a>
   </div>
    @section Scripts {

    <style>
 
        a#SignOut {
    position: absolute;
    top: 19px;
    right: 40px;
    font-size: large;
}
    </style>
 
}