AgileConnect/Controllers/ARMAppsController.cs
using AgileConnect.EncrDecr.cs;
using AgileConnect.Filter;
using ARMCommon.Helpers;
using ARMCommon.Interface;
using ARMCommon.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using NPOI.SS.Formula.Functions;
using Oracle.ManagedDataAccess.Client;
using StackExchange.Redis;
using System;
using System.Data;
using System.Data.Odbc;
using System.Data.SqlClient;

namespace AgileConnect.Controllers
{
    [ServiceFilter(typeof(SessionActionFilter))]
    [Authorize]
    public class ARMAppsController : Controller
    {
        private readonly IConfiguration _config;
        private readonly DataContext _context;
        private readonly IRedisHelper _redis;
        private readonly Utils _common;
        private string privateKey = EncDec.RefreshKey(16);
        private readonly IRedisConnection _redisConn;

        public ARMAppsController(IConfiguration config, IRedisHelper redis, DataContext context, Utils common, IRedisConnection redisConn)
        {
            _config = config;
            _redis = redis;
            _context = context;
            _common = common;
            _redisConn = redisConn;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ARMApp model)
        {
            if (ModelState.IsValid)
            {
                model.modifiedon = DateTime.Now;
                string rediskey = $"{Constants.REDIS_PREFIX.ARMRedisConfiguration.ToString()}_{model.AppName}";
                string dbkey = $"{Constants.DB_PREFIX.ARMConnectionString.ToString()}_{model.AppName}";

                // Clear existing Redis cache keys and values
                await ClearAllRedisCacheAsync();

                model.PrivateKey = privateKey;
                model.ConnectionName = EncDec.Encrypt(model.ConnectionName, privateKey);
                model.DataBase = EncDec.Encrypt(model.DataBase, privateKey);
                model.DBVersion = EncDec.Encrypt(model.DBVersion, privateKey);
                model.UserName = EncDec.Encrypt(model.UserName, privateKey);
                model.Password = EncDec.Encrypt(model.Password, privateKey);
                model.RedisIP = EncDec.Encrypt(model.RedisIP, privateKey);
                model.RedisPassword = EncDec.Encrypt(model.RedisPassword, privateKey);
                if (model.AppLogoBase64 == null || model.AppLogoBase64.Length == 0)
                {
                    return BadRequest("File not found");
                }
                using (var memoryStream = new MemoryStream())
                {
                    await model.AppLogoBase64.CopyToAsync(memoryStream);
                    var fileBytes = memoryStream.ToArray();
                    model.AppLogo = Convert.ToBase64String(fileBytes);
                }

                _context.Add(model);
                await _context.SaveChangesAsync();
                await _redis.StringSetAsync(rediskey, _common.GetRedisConnections(model.RedisIP, model.RedisPassword));
                await _redis.StringSetAsync(dbkey, _common.GetDBConnections(model.DataBase, model.UserName, model.Password, model.DBVersion,model.Sqlversion, model.ConnectionName));
                return RedirectToAction("List");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string appName)
        {
            var userGroup = GetUserGroupById(appName);
            var Key = userGroup.PrivateKey;
            if (Key != null)
            {
                userGroup.ConnectionName = EncDec.Decrypt(userGroup.ConnectionName, Key);
                userGroup.DataBase = EncDec.Decrypt(userGroup.DataBase, Key);
                userGroup.DBVersion = EncDec.Decrypt(userGroup.DBVersion, Key);
                userGroup.UserName = EncDec.Decrypt(userGroup.UserName, Key);
                userGroup.Password = EncDec.Decrypt(userGroup.Password, Key);
                userGroup.RedisIP = EncDec.Decrypt(userGroup.RedisIP, Key);
                userGroup.RedisPassword = EncDec.Decrypt(userGroup.RedisPassword, Key);

                var con = _common.GetRedisConnections(userGroup.RedisIP, userGroup.RedisPassword);
                string dbConnectionString = await _common.GetDBConfiguration(appName);
                var redisConfig = await _redisConn.GetRedisConfiguration(appName);
            }
            return View(userGroup);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string appName, ARMApp model)
        {
            if (appName != model.AppName)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    model.modifiedon = DateTime.Now;
                    string rediskey = $"{Constants.REDIS_PREFIX.ARMRedisConfiguration.ToString()}_{appName}";
                    string dbkey = $"{Constants.DB_PREFIX.ARMConnectionString.ToString()}_{appName}";


                    var result = await ClearAllRedisCacheAsync();

                    model.PrivateKey = privateKey;
                    model.ConnectionName = EncDec.Encrypt(model.ConnectionName, privateKey);
                    model.DataBase = EncDec.Encrypt(model.DataBase, privateKey);
                    model.DBVersion = EncDec.Encrypt(model.DBVersion, privateKey);
                    model.UserName = EncDec.Encrypt(model.UserName, privateKey);
                    model.Password = EncDec.Encrypt(model.Password, privateKey);
                    model.RedisIP = EncDec.Encrypt(model.RedisIP, privateKey);
                    model.RedisPassword = EncDec.Encrypt(model.RedisPassword, privateKey);
                    if (model.AppLogoBase64 == null || model.AppLogoBase64.Length == 0)
                    {
                        return BadRequest("Please upload logo");
                    }
                    using (var memoryStream = new MemoryStream())
                    {
                        await model.AppLogoBase64.CopyToAsync(memoryStream);
                        var fileBytes = memoryStream.ToArray();
                        model.AppLogo = Convert.ToBase64String(fileBytes);
                    }

                    _context.Update(model);
                    await _context.SaveChangesAsync();
                    await _redis.StringSetAsync(rediskey, _common.GetRedisConnections(model.RedisIP, model.RedisPassword));
                    await _redis.StringSetAsync(dbkey, _common.GetDBConnections(model.DataBase, model.UserName, model.Password, model.DBVersion,model.Sqlversion, model.ConnectionName));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppExists(model.AppName))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("List");
            }
            return View(model);
        }

        public IActionResult List()
        {
            var appLists = AppList();
            return View(appLists);
        }

        private ARMApp GetUserGroupById(string appName)
        {
            return GetUserGroupBy(appName);
        }

        private ARMApp GetUserGroupBy(string appName)
        {
            var app = _context.ARMApps.Find(appName);
            if (app == null)
                throw new KeyNotFoundException("App not found");
            return app;
        }

        private bool AppExists(string appName)
        {
            return _context.ARMApps.Any(e => e.AppName == appName);
        }

        private IEnumerable<ARMApp> AppList()
        {
            var appList = _context.ARMApps.ToList();
            return appList;
        }

        public string ConvertToBase64(IFormFile file)
        {
            using (var memoryStream = new MemoryStream())
            {
                file.CopyTo(memoryStream);
                var fileBytes = memoryStream.ToArray();
                return Convert.ToBase64String(fileBytes);
            }
        }

        [HttpPost]
        public async Task<IActionResult> TestConnection(string dbType, string connectionString)
        {
            try
            {
                IDbConnection connection;

                if (dbType.Equals("postgre", StringComparison.OrdinalIgnoreCase))
                {
                    connection = new NpgsqlConnection(connectionString);
                }
                else if (dbType.Equals("oracle", StringComparison.OrdinalIgnoreCase))
                {
                    connection = new OracleConnection(connectionString);
                }
                else if (dbType.Equals("mssql", StringComparison.OrdinalIgnoreCase))
                {
                    connection = new SqlConnection(connectionString);
                }
                else
                {
                    return Json(new { success = false, message = "Invalid database type specified." });
                }

                connection.Open();
                connection.Close();

                return Json(new { success = true, message = "Connection Successful." });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }


        [HttpPost]
        public async Task<IActionResult> GetServerIpAndPort(string dbVersion, string uid, string pwd, string database)
        {
            string connStr = $"DSN={dbVersion};Uid={uid};Pwd={pwd};";
            string connectionString = "";
            string dataSourceName = string.Empty;

            try
            {
                using (OdbcConnection connection = new OdbcConnection(connStr))
                {

AgileConnect/Controllers/LogsController.cs
using ARMCommon.Helpers;
using ARMCommon.Interface;
using ARMCommon.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace AgileConnect.Controllers
{
    public class LogsController : Controller
    {
        private readonly IConfiguration _config;
        private readonly ITokenService _tokenService;
        private readonly DataContext _context;
        private readonly IRedisHelper _redis;
        private string generatedToken = null;


        public LogsController(IConfiguration config, ITokenService tokenService, DataContext context, IRedisHelper redis)
        {
            _config = config;
            _tokenService = tokenService;
            _context = context;
            _redis = redis;
        }

        public async Task<IActionResult> logs(string appname)
        {
            Logs logs = new Logs();
            logs.appname = appname;

            var dictlogdetails = await _redis.HashGetAllDictAsync("logdetails");
            string instanceId = dictlogdetails.ContainsKey("InstanceId") ? dictlogdetails["InstanceId"] : "";

            // Retrieve current logs from your database or data source based on the instanceId
            var currentLogs = await _context.armlogs
                .Where(x => x.instanceid == instanceId) // Filter logs by instanceId
                .Select(x => new
                {
                    x.logtime,
                    x.instanceid,
                    x.logtype,
                    x.path,
                    x.module,
                    x.logdetails
                })
                .ToListAsync();
            string apinames = dictlogdetails.ContainsKey("api") ? dictlogdetails["api"] : "";
            string servicenames = dictlogdetails.ContainsKey("service") ? dictlogdetails["service"] : "";
            ViewBag.ApiNames = apinames;
            ViewBag.serviceNames = servicenames;
            return View(logs);
        }

        [HttpPost]
        public async Task<IActionResult> StartLogging(string appname, List<string> apiNames, List<string> serviceNames)
        {
            string key = "logdetails";
            string instanceId = Guid.NewGuid().ToString();
            await _redis.HashSetAsync(key, "InstanceId", instanceId);
            await _redis.HashSetAsync(key, "api", string.Join(",", apiNames));
            await _redis.HashSetAsync(key, "service", string.Join(",", serviceNames));

            // Optionally, you can return a JSON response indicating success
            return Json(new { success = true });
        }

        [HttpPost]
        public async Task<IActionResult> StopLogging(string appname, List<string> apiNames)
        {
            string key = "logdetails";
            await _redis.KeyDeleteAsync(key);
            // Optionally, you can return a JSON response indicating success
            return Json(new { success = true });
        }

        [HttpGet]
        public async Task<IActionResult> GetAllLogs()
        {
            // Fetch specific columns (InstanceId, LogType, path, module, logdetails) from the "ARMLogs" table
            var allLogs = await _context.armlogs.Select(x => new
            {
                x.logtime,
                x.instanceid,
                x.logtype,
                x.path,
                x.module,
                x.logdetails
            }).ToListAsync();

            return Json(allLogs);
        }
        public async Task<IActionResult> GetCurrentLogs()
        {
            var dictlogdetails = await _redis.HashGetAllDictAsync("logdetails");
            string instanceId = dictlogdetails["InstanceId"];

            // Retrieve current logs from your database or data source based on the instanceId
            var currentLogs = await _context.armlogs
                .Where(x => x.instanceid == instanceId) // Filter logs by instanceId
                .Select(x => new
                {
                    x.logtime,
                    x.instanceid,
                    x.logtype,
                    x.path,
                    x.module,
                    x.logdetails
                })
                .ToListAsync();

            return Json(currentLogs);
        }

        [HttpGet]
        public async Task<IActionResult> KeyExist()
        {
            var dictlogdetails = await _redis.HashGetAllDictAsync("logdetails");
            string instanceId = dictlogdetails.ContainsKey("InstanceId") ? dictlogdetails["InstanceId"] : "";

            // Retrieve current logs from your database or data source based on the instanceId
            var currentLogs = await _context.armlogs
                .Where(x => x.instanceid == instanceId) // Filter logs by instanceId
                .Select(x => new
                {
                    x.logtime,
                    x.instanceid,
                    x.logtype,
                    x.path,
                    x.module,
                    x.logdetails
                })
                .ToListAsync();

            string apinames = dictlogdetails.ContainsKey("api") ? dictlogdetails["api"] : "";
            string[] apiNamesArray = apinames.Split(',');
            string apiNamesJson = Newtonsoft.Json.JsonConvert.SerializeObject(apiNamesArray);
            ViewBag.ApiNamesJson = apiNamesJson;
            string servicenames = dictlogdetails.ContainsKey("service") ? dictlogdetails["api"] : "";
            string[] serviceNamesArray = servicenames.Split(',');
            string serviceNamesJson = Newtonsoft.Json.JsonConvert.SerializeObject(serviceNamesArray);
            ViewBag.serviceNamesJson = serviceNamesJson;
            return Json(currentLogs);
        }

        public IActionResult GetDropdownValues()
        {
            // Read the JSON file from the wwwroot folder or any other suitable location
            var jsonPath = "D:\\Deepti\\AgileConnect\\ServiceList.Json";
            var jsonData = System.IO.File.ReadAllText(jsonPath);

            return Json(jsonData);
        }


    }
}

AgileConnect/Views/ARMApps/List.cshtml
@model IEnumerable<ARMCommon.Model.ARMApp>

@{
    ViewData["Title"] = "ARM Apps List";
}

<h3>Connected Apps</h3>
<div class="connect-app d-flex justify-content-between mt-3 mb-3">
    <div class="arm-back-list">
        <a asp-controller="ARMInstance" asp-action="Dashboard" id="redirectApp" class="redirectButton btn btn-primary" title="redirectButton">
            <span class="btn-label"><i class="fa-solid fa-arrow-left"></i></span> Back To Dashboard
        </a>
    </div>
    <div class="create-app">
        <a asp-action="Create" id="redirectApp" class="redirectButton btn btn-primary" title="redirectButton">
            <span class="btn-label"><i class="fa-solid fa-pen-to-square"></i></span> Create App
        </a>
    </div>
</div>

<hr />

@if (Model != null && Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>App Name</th>
                <th>Users</th>
                <th>UserGroups</th>
                <th>Notification Templates</th>
                <th>API Definitions</th>
                <th>SQL DataSources</th>
                @* <th>HTML Pages</th> *@
                <th>Logs</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr id="app-@item.AppName">
                    <td>
                        <a asp-action="Edit" asp-route-Appname="@item.AppName">@Html.DisplayFor(modelItem => item.AppName)</a>
                    </td>
                    <td>
                        <a asp-controller="ARMUsers" asp-action="ListByApp" asp-route-Appname="@item.AppName">
                            <i class="material-icons text-primary">person</i>
                        </a>
                    </td>
                    <td>
                        <a asp-controller="ARMUserGroups" asp-action="ListByApp" asp-route-Appname="@item.AppName">
                            <i class="material-icons">group</i>
                        </a>
                    </td>
                    <td>
                        <a asp-controller="ARMNotification" asp-action="ListByApp" asp-route-Appname="@item.AppName">
                            <i class="material-icons">notifications</i>
                        </a>
                    </td>
                    <td>
                        <a asp-controller="ARMDataSources" asp-action="APIDefinitionsList" asp-route-Appname="@item.AppName">
                            <i class="material-icons">assignment</i>
                        </a>
                    </td>
                    <td>
                        <a asp-controller="ARMDataSources" asp-action="SQLDataSourceList" asp-route-Appname="@item.AppName">
                            <i class="material-icons">storage</i>
                        </a>
                    </td>
                    @*  <td>
                    <a asp-controller="ARMHtml" asp-action="ListByApp" asp-route-Appname="@item.AppName">
                        <i class="material-icons" style="font-size: 32px;">html</i>
                    </a>
                </td> *@
                    <td>
                        <a asp-controller="Logs" asp-action="logs" asp-route-Appname="@item.AppName">
                            <i class="material-icons" style="font-size: 32px;">html</i>
                        </a>
                    </td>
                    <td>
                        <button type="button" class="btn btn-primary deleteRecordBtn" data-appname="@item.AppName">
                            <i class="fa-regular fa-trash-can"></i>
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-info" role="alert">
        No apps found.
    </div>
}

@section Scripts {
    <style>
        a#SignOut {
            position: absolute;
            top: 19px;
            right: 40px;
            font-size: large;
        }

        a {
            text-decoration: none;
        }

        th, td {
            text-align: center;
        }

        h3 {
            font-size: 20px;
            letter-spacing: 2px;
            text-transform: uppercase;
        }
    </style>
    <script>
        $(document).ready(function () {
            $('.deleteRecordBtn').click(function () {
                var appName = $(this).data('appname');
                if (confirm("Are you sure you want to delete this record?")) {
                    $.ajax({
                        url: '@Url.Action("Delete", "ARMApps")',
                        type: 'POST',
                        data: { appName: appName },
                        success: function (result) {
                            if (result.success) {
                                alert(result.message);
                                window.location.href = '@Url.Action("List", "ARMApps")';
                            } else {
                                alert("Failed to delete record: " + result.message);
                            }
                        },
                        error: function (xhr, status, error) {
                            alert("Error during delete operation: " + error);
                        }
                    });
                }
            });
        });
    </script>
}