AgileConnect/Controllers/ARMAppsController.cs
using AgileConnect.EncrDecr.cs;
using AgileConnect.Filter;
using ARMCommon.Helpers;
using ARMCommon.Interface;
using ARMCommon.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using NPOI.SS.Formula.Functions;
using Oracle.ManagedDataAccess.Client;
using StackExchange.Redis;
using System;
using System.Data;
using System.Data.Odbc;
using System.Data.SqlClient;

namespace AgileConnect.Controllers
{
    [ServiceFilter(typeof(SessionActionFilter))]
    [Authorize]
    public class ARMAppsController : Controller
    {
        private readonly IConfiguration _config;
        private readonly DataContext _context;
        private readonly IRedisHelper _redis;
        private readonly Utils _common;
        private string privateKey = EncDec.RefreshKey(16);
        private readonly IRedisConnection _redisConn;

        public ARMAppsController(IConfiguration config, IRedisHelper redis, DataContext context, Utils common, IRedisConnection redisConn)
        {
            _config = config;
            _redis = redis;
            _context = context;
            _common = common;
            _redisConn = redisConn;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ARMApp model)
        {
            if (ModelState.IsValid)
            {
                model.modifiedon = DateTime.Now;
                string rediskey = $"{Constants.REDIS_PREFIX.ARMRedisConfiguration.ToString()}_{model.AppName}";
                string dbkey = $"{Constants.DB_PREFIX.ARMConnectionString.ToString()}_{model.AppName}";

                // Clear existing Redis cache keys and values
                await ClearAllRedisCacheAsync();

                model.PrivateKey = privateKey;
                model.ConnectionName = EncDec.Encrypt(model.ConnectionName, privateKey);
                model.DataBase = EncDec.Encrypt(model.DataBase, privateKey);
                model.DBVersion = EncDec.Encrypt(model.DBVersion, privateKey);
                model.UserName = EncDec.Encrypt(model.UserName, privateKey);
                model.Password = EncDec.Encrypt(model.Password, privateKey);
                model.RedisIP = EncDec.Encrypt(model.RedisIP, privateKey);
                model.RedisPassword = EncDec.Encrypt(model.RedisPassword, privateKey);
                if (model.AppLogoBase64 == null || model.AppLogoBase64.Length == 0)
                {
                    return BadRequest("File not found");
                }
                using (var memoryStream = new MemoryStream())
                {
                    await model.AppLogoBase64.CopyToAsync(memoryStream);
                    var fileBytes = memoryStream.ToArray();
                    model.AppLogo = Convert.ToBase64String(fileBytes);
                }

                _context.Add(model);
                await _context.SaveChangesAsync();
                await _redis.StringSetAsync(rediskey, _common.GetRedisConnections(model.RedisIP, model.RedisPassword));
                await _redis.StringSetAsync(dbkey, _common.GetDBConnections(model.DataBase, model.UserName, model.Password, model.DBVersion,model.Sqlversion, model.ConnectionName));
                return RedirectToAction("List");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string appName)
        {
            var userGroup = GetUserGroupById(appName);
            var Key = userGroup.PrivateKey;
            if (Key != null)
            {
                userGroup.ConnectionName = EncDec.Decrypt(userGroup.ConnectionName, Key);
                userGroup.DataBase = EncDec.Decrypt(userGroup.DataBase, Key);
                userGroup.DBVersion = EncDec.Decrypt(userGroup.DBVersion, Key);
                userGroup.UserName = EncDec.Decrypt(userGroup.UserName, Key);
                userGroup.Password = EncDec.Decrypt(userGroup.Password, Key);
                userGroup.RedisIP = EncDec.Decrypt(userGroup.RedisIP, Key);
                userGroup.RedisPassword = EncDec.Decrypt(userGroup.RedisPassword, Key);

                var con = _common.GetRedisConnections(userGroup.RedisIP, userGroup.RedisPassword);
                string dbConnectionString = await _common.GetDBConfiguration(appName);
                var redisConfig = await _redisConn.GetRedisConfiguration(appName);
            }
            return View(userGroup);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string appName, ARMApp model)
        {
            if (appName != model.AppName)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    model.modifiedon = DateTime.Now;
                    string rediskey = $"{Constants.REDIS_PREFIX.ARMRedisConfiguration.ToString()}_{appName}";
                    string dbkey = $"{Constants.DB_PREFIX.ARMConnectionString.ToString()}_{appName}";


                    var result = await ClearAllRedisCacheAsync();

                    model.PrivateKey = privateKey;
                    model.ConnectionName = EncDec.Encrypt(model.ConnectionName, privateKey);
                    model.DataBase = EncDec.Encrypt(model.DataBase, privateKey);
                    model.DBVersion = EncDec.Encrypt(model.DBVersion, privateKey);
                    model.UserName = EncDec.Encrypt(model.UserName, privateKey);
                    model.Password = EncDec.Encrypt(model.Password, privateKey);
                    model.RedisIP = EncDec.Encrypt(model.RedisIP, privateKey);
                    model.RedisPassword = EncDec.Encrypt(model.RedisPassword, privateKey);
                    if (model.AppLogoBase64 == null || model.AppLogoBase64.Length == 0)
                    {
                        return BadRequest("Please upload logo");
                    }
                    using (var memoryStream = new MemoryStream())
                    {
                        await model.AppLogoBase64.CopyToAsync(memoryStream);
                        var fileBytes = memoryStream.ToArray();
                        model.AppLogo = Convert.ToBase64String(fileBytes);
                    }

                    _context.Update(model);
                    await _context.SaveChangesAsync();
                    await _redis.StringSetAsync(rediskey, _common.GetRedisConnections(model.RedisIP, model.RedisPassword));
                    await _redis.StringSetAsync(dbkey, _common.GetDBConnections(model.DataBase, model.UserName, model.Password, model.DBVersion,model.Sqlversion, model.ConnectionName));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppExists(model.AppName))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("List");
            }
            return View(model);
        }

        public IActionResult List()
        {
            var appLists = AppList();
            return View(appLists);
        }

        private ARMApp GetUserGroupById(string appName)
        {
            return GetUserGroupBy(appName);
        }

        private ARMApp GetUserGroupBy(string appName)
        {
            var app = _context.ARMApps.Find(appName);
            if (app == null)
                throw new KeyNotFoundException("App not found");
            return app;
        }

        private bool AppExists(string appName)
        {
            return _context.ARMApps.Any(e => e.AppName == appName);
        }

        private IEnumerable<ARMApp> AppList()
        {
            var appList = _context.ARMApps.ToList();
            return appList;
        }

        public string ConvertToBase64(IFormFile file)
        {
            using (var memoryStream = new MemoryStream())
            {
                file.CopyTo(memoryStream);
                var fileBytes = memoryStream.ToArray();
                return Convert.ToBase64String(fileBytes);
            }
        }

        [HttpPost]
        public async Task<IActionResult> TestConnection(string dbType, string connectionString)
        {
            try
            {
                IDbConnection connection;

                if (dbType.Equals("postgre", StringComparison.OrdinalIgnoreCase))
                {
                    connection = new NpgsqlConnection(connectionString);
                }
                else if (dbType.Equals("oracle", StringComparison.OrdinalIgnoreCase))
                {
                    connection = new OracleConnection(connectionString);
                }
                else if (dbType.Equals("mssql", StringComparison.OrdinalIgnoreCase))
                {
                    connection = new SqlConnection(connectionString);
                }
                else
                {
                    return Json(new { success = false, message = "Invalid database type specified." });
                }

                connection.Open();
                connection.Close();

                return Json(new { success = true, message = "Connection Successful." });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }


        [HttpPost]
        public async Task<IActionResult> GetServerIpAndPort(string dbVersion, string uid, string pwd, string database)
        {
            string connStr = $"DSN={dbVersion};Uid={uid};Pwd={pwd};";
            string connectionString = "";
            string dataSourceName = string.Empty;

            try
            {
                using (OdbcConnection connection = new OdbcConnection(connStr))
                {

AgileConnect/Controllers/ARMInstanceController.cs
using ARMCommon.Helpers;
using ARMCommon.Interface;
using ARMCommon.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Security.Cryptography;
using System.Text;

namespace AgileConnect.Controllers
{
    [Authorize]

    public class ARMInstanceController : Controller
    {
        private string ARMConfigFilePath;
        private readonly IRedisHelper _redis;
        private readonly IConfiguration _config;
        private readonly DataContext _context;
        public ARMInstanceController(IConfiguration config, IRedisHelper redis, DataContext context)
        {
            _config = config;
            _context = context;
            ARMConfigFilePath = _config["ARMConfigFilePath"];
            _redis = redis;

        }


        public ActionResult Dashboard()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int instanceId)
        {
            try
            {
                var serviceLog = await _context.ARMServiceLogs.FirstOrDefaultAsync(x => x.InstanceID == instanceId);

                if (serviceLog == null)
                {
                    return Json(new { success = false, message = "Record not found." });
                }

                _context.ARMServiceLogs.Remove(serviceLog);
                await _context.SaveChangesAsync();

                return Json(new { success = true, message = "Record deleted successfully." });
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Exception during delete action: {ex.Message}");
                return Json(new { success = false, message = $"An error occurred while deleting the record: {ex.Message}" });
            }
        }




        public ActionResult service()
        {
            var ServiceList = _context.ARMServiceLogs.ToList();
            return View(ServiceList);
        }

        public ActionResult Configure()
        {
            if (System.IO.File.Exists(ARMConfigFilePath))
            {
                string strJSON = String.Empty;

                var fileStream = new FileStream(ARMConfigFilePath, FileMode.Open, FileAccess.Read, FileShare.None);
                using (var streamReader = new StreamReader(fileStream, Encoding.UTF8))

                {
                    strJSON = streamReader.ReadToEnd();
                    var jObject = JObject.Parse(strJSON);

                    var keyData = new
                    {
                        keyInterval = jObject["KeyData"]?["KeyInterval"]?.ToString(),
                        privateKey = jObject["KeyData"]?["PrivateKey"]?.ToString()
                    };



                    var emailGateway = new
                    {
                        From = jObject["emailGateway"]?["From"]?.ToString(),
                        SmtpServer = jObject["emailGateway"]?["SmtpServer"]?.ToString(),
                        Port = jObject["emailGateway"]?["Port"]?.ToString(),
                        Username = jObject["emailGateway"]?["Username"]?.ToString(),
                        Password = jObject["emailGateway"]?["Password"]?.ToString(),
                        Server = jObject["emailGateway"]?["Server"]?.ToString()

                    };


                    var smsGateway = new
                    {
                        userto = jObject["SMSGateway"]?["userto"]?.ToString(),
                        userfrom = jObject["SMSGateway"]?["userfrom"]?.ToString(),
                        message = jObject["SMSGateway"]?["message"]?.ToString()

                    };


                    var whatsappLogin = new
                    {
                        Mobile = jObject["WhatsappLogin"]?["Mobile"]?.ToString(),
                        AuthCode = jObject["WhatsappLogin"]?["AuthCode"]?.ToString()

                    };

                    var adminInstance = new
                    {
                        admin = jObject["AdminInstance"]?["admin"]?.ToString(),
                        password = jObject["AdminInstance"]?["Password"]?.ToString(),
                        adminEmailId = jObject["AdminInstance"]?["AdminEmailId"]?.ToString()

                    };


                    var ARM = new
                    {
                        EmailGateway = emailGateway,
                        SMSGateway = smsGateway,
                        WhatsappLogin = whatsappLogin,
                        AdminInstance = adminInstance,
                        KeyData = keyData

                    };


                    var decrStrJSON = JsonConvert.SerializeObject(ARM, Formatting.Indented);
                    ViewBag.ARMText = decrStrJSON ?? String.Empty;

                }
            }
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Configure(ARMModel model)
        {
            var privateKey = RefreshKey(16);
            var emailGateway = new
            {
                From = model.From,
                SmtpServer = model.SmtpServer,
                Port = model.Portno,
                Username = model.Username,
                Password = model.Password,
                Server = model.Server
            };


            var smsGateway = new
            {
                userto = model.UserTo,
                userfrom = model.UserFrom,
                message = model.Message

            };

            var whatsappLogin = new
            {
                Mobile = model.MobileNo,
                AuthCode = model.AuthCode

            };

            var adminInstance = new
            {
                admin = model.Admin,
                Password = model.loginPassword,
                AdminEmailId = model.AdminEmailId

            };
            var keyData = new
            {
                KeyInterval = model.KeyInterval,
                PrivateKey = privateKey
            };


            var messageObjToLog = new
            {
                emailGateway = emailGateway,
                SMSGateway = smsGateway,
                WhatsappLogin = whatsappLogin,
                AdminInstance = adminInstance,
                KeyData = keyData
            };

            StreamWriter sw = new StreamWriter(ARMConfigFilePath);
            var messages = JsonConvert.SerializeObject(messageObjToLog, Formatting.Indented);
            //IDatabase db = _redis.GetDatabase();

            //set value in redis 
            var key = "ARM-INSTANCE-CONFIG";
            await _redis.StringSetAsync(key, messages);
            sw.WriteLine(messages);

            //Close the file
            sw.Close();

            return RedirectToAction("Configure");
        }

        public static string RefreshKey(int size)
        {
            char[] chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890".ToCharArray();

            byte[] data = new byte[4 * size];
            using (var crypto = RandomNumberGenerator.Create())
            {
                crypto.GetBytes(data);
            }
            StringBuilder result = new StringBuilder(size);
            for (int i = 0; i < size; i++)
            {
                var rnd = BitConverter.ToUInt32(data, i * 4);
                var idx = rnd % chars.Length;

                result.Append(chars[idx]);
            }

            return result.ToString();
        }

    }




}

AgileConnect/Views/ARMInstance/Configure.cshtml
@model ARMCommon.Model.ARMModel
@{
    ViewData["Title"] = "ConfigureUsers";
   var Jsontext = ViewBag.ARMText != null ? ViewBag.ARMText :"";
}

<h2>ARM Instance </h2>
           
   @* <a asp-controller="ARMSignIn" asp-action="SignOut" id="SignOut" class="redirectButton" title="redirectButton"> Sign Out </a>
 *@
   @* <div class="col-sm-6"> 
    <a asp-controller="ARMApps" asp-action="List" id="redirectApp" class="redirectButton" title="redirectButton"> View Connected Apps </a>
   </div>*@


 
<div class="container p-4">
    <div class="accordion" id="agile-connect-arm">
        <form asp-action="Configure">
            <div class="arm-Instance d-flex justify-content-between mt-3 mb-3">
                <div class="view-connect">
                    <a asp-controller="ARMInstance" asp-action="Dashboard" id="redirectApp" class="redirectButton btn btn-primary" title="redirectButton"><span class="btn-label"><i class="fa-solid fa-link"></i></span> Back To Dashboard </a>
                </div>
                <div class="arm-configure">
                    <input type="submit" value="Configure" class="btn btn-primary">
                </div>
            </div>

            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="accordion-item rounded-3 border-0 shadow mb-2">
                <h3 class="accordion-header">
                    <button class="accordion-button border-bottom collapsed fw-semibold" type="button"
                            data-bs-toggle="collapse" data-bs-target="#email-gateways" aria-expanded="false"
                            aria-controls="email-gateways">
                        &#11162 Email gateways
                    </button>
                </h3>
            <div id="email-gateways" class="accordion-collapse collapse show" data-bs-parent="#agile-connect-arm">
               <div class="accordion-body">
              <div class="input-group">
            <div class="form-group col-md-6">
                <label asp-for="From" class="control-label"> From</label>
                   <div class = "col-md-8">
                    <input asp-for="From" id="txtfrom" class="form-control" />
                    <span asp-validation-for="From" class="text-danger"></span>
            </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="SmtpServer" class="control-label"> SmtpServer</label>
                <div class="col-md-8">
                    <input asp-for="SmtpServer" id="txtSmtpServer" class="form-control" />
                    <span asp-validation-for="SmtpServer" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Portno" class="control-label"> Port No.</label>
                 <div class = "col-md-8"> 
                <input asp-for="Portno" id="txtport" class="form-control" />
                <span asp-validation-for="Portno" class="text-danger"></span>
            </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Username" class="control-label"> User Id</label>
                 <div class = "col-md-8">
                    <input asp-for="Username" id="txtUsername" class="form-control" />
                    <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Password" class="control-label"> Password</label>
                <div class="col-md-8">
                    <input asp-for="Password" id="txtPassword" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Server" class="control-label">Server</label>
                <div class="col-md-8">
                    <input asp-for="Server" id="txtServer" class="form-control" />
                    <span asp-validation-for="Server" class="text-danger"></span>
                </div>
            </div>
            </div>
            </div>
            </div>
            </div>

            <div class="accordion-item rounded-3 border-0 shadow mb-2">
                <h3 class="accordion-header">
                    <button class="accordion-button border-bottom collapsed fw-semibold" type="button"
                            data-bs-toggle="collapse" data-bs-target="#sms-gateway" aria-expanded="false"
                            aria-controls="sms-gateway">
                        &#11162 SMS Gateway
                    </button>
                </h3>
                <div id="sms-gateway" class="accordion-collapse collapse" data-bs-parent="#agile-connect-arm">
                    <div class="accordion-body">
              <div class="input-group">
            <div class="form-group col-md-6">
                <label asp-for="UserTo" class="control-label"> To</label>
                 <div class = "col-md-8"> 
                <input asp-for="UserTo" id="txtuserto" class="form-control" />
                <span asp-validation-for="UserTo" class="text-danger"></span>
            </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="UserFrom" class="control-label"> From</label>
                 <div class = "col-md-8"> 
                <input asp-for="UserFrom"  id= "txtuserfrom" class="form-control" />
                <span asp-validation-for="UserFrom" class="text-danger"></span>
            </div>
            </div>
              <div class="form-group col-md-6">
                <label asp-for="Message" class="control-label"> Message</label>
                 <div class = "col-md-8"> 
                <input asp-for="Message" id="txtMessage" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
         </div>
         </div>
         </div>
         </div>
         </div>

            <div class="accordion-item rounded-3 border-0 mb-2 shadow">
                <h3 class="accordion-header">
                    <button class="accordion-button border-bottom collapsed fw-semibold" type="button"
                            data-bs-toggle="collapse" data-bs-target="#whatsapp-log" aria-expanded="false"
                            aria-controls="whatsapp-log">
                        &#11162 WhatsApp login Details
                    </button>
                </h3>
                <div id="whatsapp-log" class="accordion-collapse collapse" data-bs-parent="#agile-connect-arm">
                    <div class="accordion-body">
              <div class="input-group">
               <div class="form-group col-md-6">
                <label asp-for="MobileNo" class="control-label"> Mobile No.</label>
                 <div class = "col-md-8"> 
                <input asp-for="MobileNo" id="txtMobNo" class="form-control" />
                <span asp-validation-for="MobileNo" class="text-danger"></span>
            </div>
            </div>
              <div class="form-group col-md-6">
                <label asp-for="AuthCode" class="control-label">Auth Code</label>
                 <div class = "col-md-8"> 
                <input asp-for="AuthCode" id="txtauthcode" class="form-control" />
                <span asp-validation-for="AuthCode" class="text-danger"></span>
            </div>
            </div>
            </div>
            </div>
            </div>
            </div>
            <div class="accordion-item rounded-3 border-0 mb-2 shadow">
                <h3 class="accordion-header">
                    <button class="accordion-button border-bottom collapsed fw-semibold" type="button"
                            data-bs-toggle="collapse" data-bs-target="#admin-details" aria-expanded="false"
                            aria-controls="admin-details">
                        &#11162 Admin Details
                    </button>
                </h3>
                <div id="admin-details" class="accordion-collapse collapse" data-bs-parent="#agile-connect-arm">
                    <div class="accordion-body">
              <div class="input-group">
                 <div class="form-group col-md-6">
                <label asp-for="Admin" class="control-label"> Admin</label>
                 <div class = "col-md-8"> 
                <input asp-for="Admin" id="txtadmin" class="form-control" />
                <span asp-validation-for="Admin" class="text-danger"></span>
            </div>
            </div>
              <div class="form-group col-md-6">
                <label asp-for="loginPassword" class="control-label">loginPassword</label>
                 <div class = "col-md-8">
                    <input asp-for="loginPassword" id="txtloginpsswrd" class="form-control" />
                    <span asp-validation-for="loginPassword" class="text-danger"></span>
            </div>
            </div>
                          <div class="form-group col-md-6">
                <label asp-for="AdminEmailId" class="control-label"> Email Address</label>
                 <div class = "col-md-8"> 
                <input asp-for="AdminEmailId" id="txtAdminEmail"  class="form-control" />
                <span asp-validation-for="AdminEmailId" class="text-danger"></span>
            </div>
            </div>
      </div>
      </div>
      </div>
      </div>
            <div class="accordion-item rounded-3 border-0 mb-2 shadow">
                <h3 class="accordion-header">
                    <button class="accordion-button border-bottom collapsed fw-semibold" type="button"
                            data-bs-toggle="collapse" data-bs-target="#key-details" aria-expanded="false"
                            aria-controls="key-details">
                        &#11162 Key
                    </button>
                </h3>
                <div id="key-details" class="accordion-collapse collapse" data-bs-parent="#agile-connect-arm">
                 <div class="accordion-body">
              <div class="input-group">
               <div class="form-group col-md-6">
                <label asp-for="KeyInterval" class="control-label">Key Interval</label>
                 <div class = "col-md-8"> 
                <input asp-for="KeyInterval" id="txtkeyInterval"  class="form-control" />
                <span asp-validation-for="KeyInterval" class="text-danger"></span>
              </div>
            </div>           
            <div class="form-group col-md-6">
             
                <input type="submit" value="Refresh Key" class="btn btn-secondary" />
            </div>
             <div class="form-group col-md-6">
                <label asp-for="PrivateKey" class="control-label">Key</label>
                 <div class = "col-md-8"> 
                <input asp-for="PrivateKey" ReadOnly="true" id="txtkey"  class="form-control" />
                </div>
            </div>
       </div>
 </div>
 </div>
 </div>
            @*<div class="form-group">
                <input type="submit" value="Configure" class="btn btn-primary" />
            </div>*@

        </form>
    </div>
    </div>
 
 

@section Scripts {

    <style>

        .form-group.col-md-6 {
            margin-top: 10px;
            margin-bottom: 15px;
        }

        label {
            margin-left: 0;
            font-weight: 500;
            margin-bottom: 10px;
        }

        h2 {
            font-size: 20px;
            letter-spacing: 2px;
        }

        span.btn-label {
            padding: 7.6px 12px;
            background: rgba(0, 0, 0, 0.15);
            position: relative;
            left: -12px;
            border-radius: 3px 0px 0px 3px;
        }

        label {
            margin-left: 15px;
            font-weight: 500;
        }

        input.btn.btn-secondary {
            margin: 16px;
        }

        a {
            margin-left: 40px;
            font-weight: 600;
            text-decoration:none;
        }

            a#SignOut {
                position: absolute;
                top: 25px;
                right: 40px;
                font-size: large;
            }

        .p-4 {
            padding: 1rem !important;
        }
    </style>

    <script type="text/javascript">
 $(document).ready(function () {

     
     var JObj = '';
        JObj = JSON.stringify(@Html.Raw(ViewBag.ARMText));
      
   
        if (JObj != undefined && JObj!='') {
         JObj = JSON.parse(JObj);
            console.log(JObj);
           $("#txtfrom").val(JObj.EmailGateway.From);
           $("#txtSmtpServer").val(JObj.EmailGateway.SmtpServer);
           $("#txtPort").val(JObj.EmailGateway.Port);
           $("#txtUsername").val(JObj.EmailGateway.Username);
           $("#txtPassword").val(JObj.EmailGateway.Password);
           $("#txtServer").val(JObj.EmailGateway.Server);
          $("#txtuserto").val(JObj.SMSGateway.userto);
          $("#txtuserfrom").val(JObj.SMSGateway.userfrom);
          $("#txtMessage").val(JObj.SMSGateway.message);
          $("#txtMobNo").val(JObj.WhatsappLogin.Mobile);
          $("#txtauthcode").val(JObj.WhatsappLogin.AuthCode);
           $("#txtadmin").val(JObj.AdminInstance.admin);
          $("#txtloginpsswrd").val(JObj.AdminInstance.loginPassword);
          $("#txtAdminEmail").val(JObj.AdminInstance.adminEmailId);
           $("#txtkeyInterval").val(JObj.KeyData.keyInterval);
          $("#txtkey").val(JObj.KeyData.privateKey);
          
       
  
     }
    });
 

</script>
}